# Generated by Django 6.0.2 on 2026-05-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_city_alter_order_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'في الانتظار'), ('paid', 'تم الدفع'), ('shipped', 'تم الشحن'), ('delivered', 'تم التوصيل'), ('canceled', 'تم الالغاء'), ('failed', 'فشل الدفع'), ('refunded', 'تم الاسترداد')], default='pending', max_length=50),
        ),
    ]
